import FiscalFixture from './FiscalFixture';
import { createRoot } from 'react-dom/client';
import WebFixTheme from '../../src/components/ui/WebFixTheme';
import ThemeFixture from './ThemeFixture';
import '../../src/index.css';
import FinanceModule from '../../src/components/finances/FinanceModule';
import TransactionForm from '../../src/components/finances/TransactionForm';
import InventoryModule from '../../src/components/inventory/InventoryModule';
import { setTenantId } from '../../src/firebase';
import { normalizeProduct, makeCartItem } from '../../src/services/productModel';
import { fixtureProducts, fixtureClient } from './firebase-fixture';
setTenantId('test');
const products = fixtureProducts.map(p => normalizeProduct(p));
const mode = new URLSearchParams(location.search).get('mode');
const showToast = (message, type) => { globalThis.__lastToast = { message, type }; document.getElementById('test-status').textContent = message; };
const transaction = { type: 'ingreso', documentType: 'nota_venta', date: '2026-09-14', thirdPartyId: fixtureClient.id, thirdParty: fixtureClient, items: [makeCartItem(products[0])], total: 23, baseImponible: 20, ivaValor: 3, paymentsBreakdown: { efectivo: 23, transferencia: 0, tarjeta: 0, cruce_cuentas: 0 }, paymentStatus: 'pagado' };
const emptyTransaction = { type: 'ingreso', documentType: 'factura', date: '2026-09-14', thirdPartyId: '', items: [], total: 0 };
const unpaidTransaction = { ...transaction, documentType: 'factura', paymentsBreakdown: { efectivo: 0, transferencia: 0, tarjeta: 0, cruce_cuentas: 0 }, paymentStatus: 'pendiente' };
createRoot(document.getElementById('root')).render(<WebFixTheme><div id="test-status" role="status" className="fixed bottom-0 left-0 z-[500] bg-surface-card text-text-primary p-2 text-sm pointer-events-none" /><div className="p-6">{mode?.startsWith('sri-') ? <FiscalFixture showToast={showToast} pending={mode === 'sri-pending'} /> : mode === 'theme' ? <ThemeFixture /> : mode?.startsWith('inventory') ? <InventoryModule initialSubTab={mode === 'inventory-services' ? 'servicios' : undefined} showToast={showToast} /> : mode?.startsWith('admin') ? <TransactionForm tx={mode === 'admin-empty' ? emptyTransaction : mode === 'admin-unpaid' ? unpaidTransaction : transaction} products={products} thirdParties={[fixtureClient]} showToast={showToast} db={{}} appId="test" onClose={() => { globalThis.__closed = true; }} onSaved={data => { globalThis.__saved = data; }} /> : <FinanceModule mode={mode === 'finance' ? 'contabilidad' : mode === 'purchases' ? 'compras' : 'ventas'} initialSubTab={new URLSearchParams(location.search).get('tab') || (mode === 'pos' ? 'pos' : undefined)} products={products} thirdParties={[fixtureClient]} transactions={[]} usuario={{ uid: 'tester', email: 'pruebas@example.invalid' }} showToast={showToast} />}</div></WebFixTheme>);
