import { createServer } from 'vite';
import { createRequire } from 'node:module';
import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const bundle = process.env.WEBFIX_BROWSER_MODULES || 'C:/Users/WEB FIX/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const { chromium } = createRequire(path.join(bundle, 'package.json'))('playwright');
const fixture = path.resolve('tests/browser/firebase-fixture.js');
const server = await createServer({ configFile: false, cacheDir: 'node_modules/.vite-browser-tests', resolve: { alias: { 'firebase/firestore': fixture, 'firebase/storage': fixture, 'firebase/auth': fixture } }, server: { host: '127.0.0.1', port: 5178, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const errors = [];
page.setDefaultTimeout(30000);
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => {
  if (message.type() === 'error' && !message.text().includes('favicon.ico')) errors.push(message.text());
});
await page.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:5178') ? route.continue() : route.abort());
fs.mkdirSync('docs/design-review/screenshots', { recursive: true });
try {
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=admin-empty');
  await page.getByRole('button', { name: 'Emitir Factura Electrónica (SRI)' }).click();
  const adminIssues = page.getByRole('dialog', { name: 'ALERTA' });
  await adminIssues.getByText('INGRESA CLIENTE').waitFor();
  await adminIssues.getByText('AGREGA PRODUCTO').waitFor();
  await adminIssues.getByRole('button', { name: 'Ingresar Cliente' }).click();
  assert.equal(await page.locator('#admin-client-search').evaluate(el => el === document.activeElement), true);
  console.log('PASS: venta administrativa explica faltantes y enfoca cliente');

  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=admin-unpaid');
  await page.getByRole('button', { name: 'Emitir Factura Electrónica (SRI)' }).click();
  const paymentIssues = page.getByRole('dialog', { name: 'ALERTA' });
  await paymentIssues.getByText('INGRESA PAGO').waitFor();
  await paymentIssues.getByRole('button', { name: 'Ingresar Pago' }).click();
  assert.equal(await page.locator('#admin-payment-section').evaluate(el => el === document.activeElement), true);
  console.log('PASS: venta administrativa pide pago con alerta breve y enfoca medio de pago');

  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=pos');
  await page.getByText('Teclado USB', { exact: true }).first().waitFor();
  await page.getByText('Para cobrar').waitFor();
  await page.getByText('Falta producto').waitFor();
  await page.getByText('Falta cliente').waitFor();
  await page.getByRole('button', { name: 'Ver qué falta' }).click();
  await page.getByRole('dialog', { name: 'ALERTA' }).getByRole('button', { name: 'Cerrar' }).click();
  await page.keyboard.press('F12');
  const posIssues = page.getByRole('dialog', { name: 'ALERTA' });
  await posIssues.getByText('AGREGA PRODUCTO').waitFor();
  await posIssues.getByText('INGRESA CLIENTE').waitFor();
  await posIssues.getByRole('button', { name: 'Agregar Producto' }).click();
  assert.equal(await page.locator('#pos-search-input').evaluate(el => el === document.activeElement), true);
  await page.getByText('Teclado USB', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Consumidor Final', exact: true }).click();
  await page.keyboard.press('F12');
  await page.getByText('Seleccionar Método de Pago').waitFor();
  console.log('PASS: POS bloquea cobro incompleto y enfoca productos');

  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=admin', { timeout: 30000 });
  const description = page.getByRole('textbox', { name: 'Descripción en factura, línea 1' });
  await description.waitFor({ timeout: 30000 });
  await description.fill('Instalación y configuración personalizada');
  await page.screenshot({ path: 'docs/design-review/screenshots/venta-administrativa.png', fullPage: true });
  assert.equal(await description.inputValue(), 'Instalación y configuración personalizada');
  await page.getByRole('button', { name: 'Registrar Nota de Venta', exact: true }).click();
  await page.getByRole('button', { name: /Confirmar|Sí,|Aceptar/ }).last().click();
  await page.waitForFunction(() => !!globalThis.__saved, { timeout: 15000 });
  const saved = await page.evaluate(() => globalThis.__saved);
  assert.equal(saved.items[0].invoiceDescription, 'Instalación y configuración personalizada');
  assert.equal(saved.items[0].name, 'Teclado USB');
  assert.equal(saved.financialSyncStatus, 'complete');
  assert.equal(await page.evaluate(() => globalThis.__fixtureData.get('artifacts/test/public/data/inventory_products/product-1').stock), 7);
  console.log('PASS: venta administrativa, descripción, guardado e inventario');
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=pos');
  await page.getByText('Teclado USB', { exact: true }).first().waitFor();
  await page.getByText('Teclado USB', { exact: true }).first().click();
  await page.getByPlaceholder(/cliente/i).first().fill('Cliente');
  await page.getByText('Cliente de prueba', { exact: true }).first().click();
  await page.screenshot({ path: 'docs/design-review/screenshots/pos.png', fullPage: true });
  await page.keyboard.press('F12');
  await page.keyboard.press('F12');
  await page.getByRole('textbox', { name: 'Descripción en factura, línea 1' }).waitFor();
  await page.getByRole('button', { name: 'Cerrar', exact: true }).first().click();
  await page.getByRole('button', { name: /modificar carrito/i }).click();
  assert.ok(await page.getByText('Teclado USB', { exact: true }).count() >= 2, 'Canceling the form must preserve the POS cart');
  console.log('PASS: POS abre venta y conserva carrito al cancelar');
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=inventory');
  await page.getByRole('button', { name: /Nuevo Producto/i }).click();
  await page.getByText('Combo / Kit', { exact: true }).click();
  await page.getByRole('button', { name: /Agregar componente/i }).click();
  await page.getByRole('combobox', { name: 'Componente 1', exact: true }).click();
  await page.getByRole('option', { name: 'Teclado USB', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Cantidad del componente 1', exact: true }).fill('2');
  assert.match(await page.getByRole('combobox', { name: 'Componente 1', exact: true }).innerText(), /Teclado USB/);
  await page.screenshot({ path: 'docs/design-review/screenshots/inventario-combo.png', fullPage: true });
  console.log('PASS: inventario permite definir componentes y cantidades de un combo');
  await page.getByRole('button', { name: /Cancelar/i }).last().click();
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=inventory-services');
  await page.getByRole('button', { name: /Nuevo Servicio/i }).click();
  await page.locator('input[name="sku"]').fill('SERV-TEST');
  await page.locator('input[name="name"]').fill('Soporte digital');
  await page.locator('input[name="baseCost"]').fill('5');
  await page.locator('input[name="priceASinImpuesto"]').fill('12');
  await page.locator('input[name="priceBSinImpuesto"]').fill('18');
  await page.locator('input[name="priceCSinImpuesto"]').fill('25');
  await page.locator('select[name="taxRate"]').selectOption('15');
  assert.equal(await page.locator('input[name="priceBSinImpuesto"]').inputValue(), '18');
  await page.screenshot({ path: 'docs/design-review/screenshots/inventario-servicio-precios.png', fullPage: true });
  console.log('PASS: inventario permite precios diferenciados e IVA para servicios');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=admin');
  await page.getByText('Venta Administrativa', { exact: true }).last().waitFor();
  await page.screenshot({ path: 'docs/design-review/screenshots/radix-venta-movil.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('PASS: vista móvil sin desbordamiento; sin errores JavaScript');
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=theme');
  await page.getByRole('heading', { name: 'Controles WebFix' }).waitFor();
  await page.getByLabel('Concepto', { exact: true }).fill('Soporte encuestas');
  await page.getByLabel('Categoría', { exact: true }).click();
  await page.getByRole('option', { name: 'Producto', exact: true }).click();
  await page.getByLabel('Disponible', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Guardar prueba' }).click();
  assert.equal(await page.locator('output').textContent(), 'Soporte encuestas');
  await page.getByRole('button', { name: 'Abrir diálogo' }).click();
  await page.getByRole('dialog').waitFor();
  assert.equal(await page.getByRole('dialog').locator('.rt-TextFieldInput').evaluate(el => el === document.activeElement), true);
  for (let i = 0; i < 5; i++) {
    await page.keyboard.press('Tab');
    assert.equal(await page.getByRole('dialog').evaluate(el => el.contains(document.activeElement)), true);
  }
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.getByRole('button', { name: 'Abrir diálogo' }).evaluate(el => el === document.activeElement), true);
  await page.getByRole('tab', { name: 'Ventas', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await page.getByRole('tabpanel').getByText('Detalle de existencias').waitFor();
  assert.equal(await page.getByRole('cell', { name: '$12.50', exact: true }).count(), 1);
  await page.screenshot({ path: 'docs/design-review/screenshots/radix-controles.png', fullPage: true });
  console.log('PASS: Themes, formularios nativos, tabla, diálogo con foco/Escape y pestañas con teclado');
  for (const tab of ['resumen_financiero', 'movimientos', 'cxc', 'cxp', 'bancos', 'tarjetas', 'prestamos', 'contabilidad_tab', 'impuestos', 'reportes', 'captura']) {
    await page.goto(`http://127.0.0.1:5178/tests/browser/index.html?mode=finance&tab=${tab}`);
    await page.locator('.webfix-theme').waitFor();
    await page.waitForFunction(() => document.querySelector('.webfix-theme')?.textContent.length > 80);
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    assert.deepEqual(errors, [], `Errores al abrir ${tab}`);
  }
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=purchases&tab=compras_resumen');
  await page.getByRole('button', { name: /Registrar Compra/i }).first().waitFor();
  await page.screenshot({ path: 'docs/design-review/screenshots/radix-compras.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: apertura de 11 submódulos financieros y compras con Themes sin errores JavaScript');
} catch (error) {
  await page.screenshot({ path: 'docs/design-review/screenshots/test-failure.png', fullPage: true });
  console.error('Browser errors:', errors);
  console.error(await page.locator('body').innerText());
  throw error;
} finally { await browser.close(); await server.close(); }
