import { createServer } from 'vite';
import { createRequire } from 'node:module';
import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const bundle = process.env.WEBFIX_BROWSER_MODULES || 'C:/Users/WEB FIX/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const { chromium } = createRequire(path.join(bundle, 'package.json'))('playwright');
const fixture = path.resolve('tests/browser/firebase-fixture.js');
const server = await createServer({ configFile: false, cacheDir: 'node_modules/.vite-browser-tests', resolve: { alias: { 'firebase/firestore': fixture, 'firebase/storage': fixture, 'firebase/auth': fixture } }, server: { host: '127.0.0.1', port: 5178, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const errors = [];
page.setDefaultTimeout(10000);
page.on('pageerror', error => errors.push(error.message));
await page.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:5178') ? route.continue() : route.abort());
fs.mkdirSync('docs/design-review/screenshots', { recursive: true });
try {
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=admin');
  const description = page.getByRole('textbox', { name: 'Descripción en factura, línea 1' });
  await description.waitFor({ timeout: 30000 });
  await description.fill('Instalación y configuración personalizada');
  await page.screenshot({ path: 'docs/design-review/screenshots/venta-administrativa.png', fullPage: true });
  assert.equal(await description.inputValue(), 'Instalación y configuración personalizada');
  await page.getByRole('button', { name: 'Registrar Nota de Venta', exact: true }).click();
  await page.getByRole('button', { name: /Confirmar|Sí,|Aceptar/ }).last().click();
  await page.waitForFunction(() => !!globalThis.__saved, { timeout: 15000 });
  const saved = await page.evaluate(() => globalThis.__saved);
  assert.equal(saved.items[0].invoiceDescription, 'Instalación y configuración personalizada');
  assert.equal(saved.items[0].name, 'Teclado USB');
  assert.equal(saved.financialSyncStatus, 'complete');
  assert.equal(await page.evaluate(() => globalThis.__fixtureData.get('artifacts/test/public/data/inventory_products/product-1').stock), 7);
  console.log('PASS: venta administrativa, descripción, guardado e inventario');
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=pos');
  await page.getByText('Teclado USB', { exact: true }).first().waitFor();
  await page.getByText('Teclado USB', { exact: true }).first().click();
  await page.getByPlaceholder(/cliente/i).first().fill('Cliente');
  await page.getByText('Cliente de prueba', { exact: true }).first().click();
  await page.screenshot({ path: 'docs/design-review/screenshots/pos.png', fullPage: true });
  await page.keyboard.press('F12');
  await page.keyboard.press('F12');
  await page.getByRole('textbox', { name: 'Descripción en factura, línea 1' }).waitFor();
  await page.getByRole('button', { name: 'Cerrar', exact: true }).first().click();
  await page.getByRole('button', { name: /modificar carrito/i }).click();
  assert.ok(await page.getByText('Teclado USB', { exact: true }).count() >= 2, 'Canceling the form must preserve the POS cart');
  console.log('PASS: POS abre venta y conserva carrito al cancelar');
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=inventory');
  await page.getByRole('button', { name: /Nuevo Producto/i }).click();
  await page.getByText('Combo / Kit', { exact: true }).click();
  await page.getByRole('button', { name: /Agregar componente/i }).click();
  await page.getByRole('combobox', { name: 'Componente 1', exact: true }).selectOption('product-1');
  await page.getByRole('spinbutton', { name: 'Cantidad del componente 1', exact: true }).fill('2');
  assert.equal(await page.getByRole('combobox', { name: 'Componente 1', exact: true }).inputValue(), 'product-1');
  await page.screenshot({ path: 'docs/design-review/screenshots/inventario-combo.png', fullPage: true });
  console.log('PASS: inventario permite definir componentes y cantidades de un combo');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('http://127.0.0.1:5178/tests/browser/index.html?mode=admin');
  await page.getByText('Venta Administrativa', { exact: true }).last().waitFor();
  await page.screenshot({ path: 'docs/design-review/screenshots/venta-movil.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('PASS: vista móvil sin desbordamiento; sin errores JavaScript');
} catch (error) {
  await page.screenshot({ path: 'docs/design-review/screenshots/test-failure.png', fullPage: true });
  console.error('Browser errors:', errors);
  console.error(await page.locator('body').innerText());
  throw error;
} finally { await browser.close(); await server.close(); }
