import { forwardRef } from 'react';
import { Table as RadixTable } from '@radix-ui/themes';
export const Table = forwardRef(function Table(props, ref) { return <RadixTable.Root ref={ref} size="2" variant="surface" {...props} />; });
export const TableHeader = forwardRef(function TableHeader(props, ref) { return <RadixTable.Header ref={ref} {...props} />; });
export const TableBody = forwardRef(function TableBody(props, ref) { return <RadixTable.Body ref={ref} {...props} />; });
export const TableRow = forwardRef(function TableRow(props, ref) { return <RadixTable.Row ref={ref} {...props} />; });
export const TableHead = forwardRef(function TableHead(props, ref) { return <RadixTable.ColumnHeaderCell ref={ref} {...props} />; });
export const TableCell = forwardRef(function TableCell({ mono, style, ...props }, ref) { return <RadixTable.Cell ref={ref} style={{ ...(mono ? { fontFamily: 'var(--code-font-family)' } : {}), ...style }} {...props} />; });
export const TableFooter = forwardRef(function TableFooter(props, ref) { return <tfoot ref={ref} {...props} />; });
export const TableCaption = forwardRef(function TableCaption(props, ref) { return <caption ref={ref} {...props} />; });
export default Table;
